export interface Objeto {
    idObjeto: number,
    mejorasEquipo: string,
    codigo: string,
    disponible: number,
    eliminado: number,
    fechaAdquisicion: Date,
    observaciones: string,
    organizativa: string,
    etiqueta: string,
    Ubicacion_idUbicacion: number,
    GrupoObjetos_idGrupoObjetos: number,
    edificio: string,
    planta: string,
    ubicacion: string,
    nombre?: string,
}