export interface Objeto {
    idObjeto: number,
    mejorasEquipo: Text,
    codigo: Text,
    disponible: number,
    eliminado: number,
    fechaAdquisicion: Date,
    observaciones: Text,
    organizativa: Text,
    etiqueta: Text,
    Ubicacion_idUbicacion: number,
    GrupoObjetos_idGrupoObjetos: number,
    edificio?: Text,
    planta?: Text,
    ubicacion?: Text,
    nombre?: Text,
}