-- MySQL Script generated by MySQL Workbench
-- Tue Jul 21 10:56:53 2020
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `mydb` DEFAULT CHARACTER SET utf8 ;
USE `mydb` ;

-- -----------------------------------------------------
-- Table `mydb`.`GrupoObjetos`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`GrupoObjetos` (
  `idGrupoObjetos` INT NOT NULL,
  `cantidad` INT NULL,
  `nombre` VARCHAR(45) NULL,
  `imagen` VARCHAR(45) NULL,
  `marca` VARCHAR(45) NULL,
  `modelo` VARCHAR(45) NULL,
  `cantidadDisponible` INT NULL,
  PRIMARY KEY (`idGrupoObjetos`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Ubicacion`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Ubicacion` (
  `idUbicacion` INT NOT NULL,
  `ubicacion` VARCHAR(45) NOT NULL,
  `planta` VARCHAR(45) NOT NULL,
  `edificio` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`idUbicacion`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Objeto`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Objeto` (
  `idObjeto` INT NOT NULL,
  `mejorasEquipo` VARCHAR(45) NULL,
  `codigo` INT NULL,
  `GrupoObjetos_idGrupoObjetos` INT NOT NULL,
  `Ubicacion_idUbicacion` INT NOT NULL,
  `disponible` TINYINT NOT NULL,
  `elminado` TINYINT NULL,
  PRIMARY KEY (`idObjeto`, `GrupoObjetos_idGrupoObjetos`, `Ubicacion_idUbicacion`),
  INDEX `fk_Objeto_GrupoObjetos1_idx` (`GrupoObjetos_idGrupoObjetos` ASC) VISIBLE,
  INDEX `fk_Objeto_Ubicacion1_idx` (`Ubicacion_idUbicacion` ASC) VISIBLE,
  CONSTRAINT `fk_Objeto_GrupoObjetos1`
    FOREIGN KEY (`GrupoObjetos_idGrupoObjetos`)
    REFERENCES `mydb`.`GrupoObjetos` (`idGrupoObjetos`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Objeto_Ubicacion1`
    FOREIGN KEY (`Ubicacion_idUbicacion`)
    REFERENCES `mydb`.`Ubicacion` (`idUbicacion`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Configuracion`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Configuracion` (
  `idConfiguracion` INT NOT NULL,
  `ip` VARCHAR(45) NULL,
  `mac` VARCHAR(45) NULL,
  `boca` VARCHAR(45) NULL,
  `armario` VARCHAR(45) NULL,
  `usuario` VARCHAR(45) NULL,
  `contrasena` VARCHAR(45) NULL,
  `Objeto_idObjeto` INT NOT NULL,
  PRIMARY KEY (`idConfiguracion`),
  INDEX `fk_Configuracion_Objeto1_idx` (`Objeto_idObjeto` ASC) VISIBLE,
  CONSTRAINT `fk_Configuracion_Objeto1`
    FOREIGN KEY (`Objeto_idObjeto`)
    REFERENCES `mydb`.`Objeto` (`idObjeto`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Usuario`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Usuario` (
  `idUsuario` INT NOT NULL,
  `nombre` VARCHAR(45) NULL,
  `contrasena` VARCHAR(45) NULL,
  `correoElectronico` VARCHAR(45) NULL,
  `rango` VARCHAR(45) NULL,
  `departamento` VARCHAR(45) NULL,
  `telefono` VARCHAR(45) NULL,
  PRIMARY KEY (`idUsuario`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Prestado`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Prestado` (
  `idPrestado` INT NOT NULL,
  `retiradoPor` VARCHAR(45) NULL,
  `fechaSalida` DATE NULL,
  `fechaEntrega` DATE NULL,
  `fechaEstimadaEntrega` DATE NULL,
  `Usuario_idUsuario` INT NOT NULL COMMENT 'Enviado por\n',
  `Objeto_idObjeto` INT NOT NULL,
  `Objeto_GrupoObjetos_idGrupoObjetos` INT NOT NULL,
  `Objeto_Ubicacion_idUbicacion` INT NOT NULL,
  PRIMARY KEY (`idPrestado`, `Usuario_idUsuario`),
  INDEX `fk_Prestado_Usuario1_idx` (`Usuario_idUsuario` ASC) VISIBLE,
  INDEX `fk_Prestado_Objeto1_idx` (`Objeto_idObjeto` ASC, `Objeto_GrupoObjetos_idGrupoObjetos` ASC, `Objeto_Ubicacion_idUbicacion` ASC) VISIBLE,
  CONSTRAINT `fk_Prestado_Usuario1`
    FOREIGN KEY (`Usuario_idUsuario`)
    REFERENCES `mydb`.`Usuario` (`idUsuario`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Prestado_Objeto1`
    FOREIGN KEY (`Objeto_idObjeto` , `Objeto_GrupoObjetos_idGrupoObjetos` , `Objeto_Ubicacion_idUbicacion`)
    REFERENCES `mydb`.`Objeto` (`idObjeto` , `GrupoObjetos_idGrupoObjetos` , `Ubicacion_idUbicacion`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
